name: get-weather
version: '0.1'
summary: Get-Weather
description: |
  Get current weather for a zip code on the command line.
confinement: devmode
base: core18
grade: devel

parts:
  get-weather:
    plugin: python
    python-version: python3
    source: .

apps:
  get-weather:
    command: get-weather